// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "78ab9386-28ad-4fe7-90f0-530f0b3df8d5";  // Device ID; // Enter device ID

const char SSID[]               = "OPPOReno8T5G";    // Network SSID (name)
const char PASS[]               = "OPPO8T5G";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "XR2eMUIGk5IECQ@mH#x7s5cws";    // Secret device password

void onMessageChange();
void onUltraSonicChange();
void onLedChange();

String message;
float ultraSonic;
bool led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange);
  ArduinoCloud.addProperty(ultraSonic, READWRITE, 2 * SECONDS, onUltraSonicChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
